DetentionTrackerAIP/src/java/au/edu/uts/aip/detentiontracker/DetentionController.java
/*
 * The controller for the Detentions aspect of the web site
 */

package au.edu.uts.aip.detentiontracker;

import java.io.*;
import java.util.ArrayList;
import javax.enterprise.context.*;
import javax.inject.*;

@Named
@RequestScoped
public class DetentionController implements Serializable {

    private DetentionDTO detention = new DetentionDTO();

    public DetentionDTO getDetention() {
        return detention;
    }
    
     /**
     * Loads a detention by its unique ID
     * @param detentionID the unique detention id
     */
    public void loadDetention(int detentionID) {
        detention = new DetentionDAO().readDetention(detentionID);
    }
     
    /**
     * Creates a new detention record in the Detentions table
     * @return a redirect that takes the user back to the view detentions page
     */
    public String createDetention() {
        DetentionDAO.createDetention(detention);
        return "view?faces-redirect=true";
    }
    
    /**
     * Updates a chosen detention with new values
     * @return a redirect that takes the user back to the view detentions page
     */
    public String editDetention() {
        DetentionDAO.updateDetention(detention);
        return "view?faces-redirect=true";
    }
    
    /**
     * Deletes a chosen record from the Detentions table
     * @param detentionID the unique detention id
     * @return a redirect that takes the user back to the view detentions page
     */
    public String removeDetention(int detentionID) {
        DetentionDAO.removeDetention(detentionID);
        return "view?faces-redirect=true";
    }
    
    /**
     * Generates a complete list of current detentions from the Detentions table
     * @return an array list of detentions that is displayed on the web page
     */
    public ArrayList<DetentionDTO> getAllDetentions() {
            return new DetentionDAO().findAllDetentions();
    }
    
    /**
     * Used to determine how many detentions are currently recorded in the Detentions table
     * @return returns the amount of current detentions
     */
    public int sizeOfDetentionList(){
        return getAllDetentions().size();
    } 
}

DetentionTrackerAIP/src/java/au/edu/uts/aip/detentiontracker/LoginController.java
/*
 * The log in controller for the log in aspect for the web site
 */

package au.edu.uts.aip.detentiontracker;

import java.io.*;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Logger;
import javax.enterprise.context.*;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.*;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;

@Named
@RequestScoped
public class LoginController implements Serializable {

    private String username;
    private String password;
    private LoginDTO login = new LoginDTO();
    private Logger log = Logger.getLogger(this.getClass().getName());

    public LoginDTO getLogin(){
        return login;
    }
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
     
    /**
     * Creates a new a new user in the login table
     * @return Will either return the user to the log in page (if creation was successful)
     * OR will return user back to the register page with an error message
     * @throws NoSuchAlgorithmException This error is thrown if the password encryption fails
     */
    public String createUser()  throws NoSuchAlgorithmException  {
        if(!LoginDAO.userExists(login.getUsername())){
            //If new username does not already exists...
            LoginDAO.createUser(login);
            return "login?faces-redirect=true";
        }
        //else if it does already exists...
        log.info("Unable to create user account");
        displayMessage("Username already exists OR you have entered incorrect characters (letters & numbers only!)");
        return null;
    }
    
    /**
     * Will log the user into the web site using container managed security
     * @return Will take the user to the Welcome page or will return the user back to
     * the log in page with an error message
     */
    public String login(){
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest)context.getExternalContext().getRequest();       
        try {
            //If the log in is successful..
            request.login(username, password);
            return "welcome?faces-redirect=true";         
        } catch (ServletException e) {
            //else...
            log.info(e.toString());
            displayMessage("Username or password is incorrect!");          
            return null;
        }
    }
    
    /**
     * Displays a message on a chosen web page
     * @param message The message that is to be displayed to the user
     */
    private void displayMessage(String message) {
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage(message));
    }
    
    /**
     * Logs the user out of the web site
     * @return returns the user to the log in page
     * @throws ServletException if the servlet fails to log out
     */
    public String logout() throws ServletException {
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest)context.getExternalContext().getRequest();
        try{
            request.logout();
        }
        catch (ServletException e) {
            log.info(e.toString());
            displayMessage("Unable to log out at this time.");
        }
        return "login?faces-redirect=true";
    }
    
}

DetentionTrackerAIP/web/WEB-INF/templates/footer.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">

    <!-- This is the footer template of the website. It provides a logout function to the user -->
    
    <h:head>
        <h:outputStylesheet  name="style.css" library="css" />
    </h:head>
    <h:body >
        <br/>
        <hr></hr>
        <p align="Center"> <h:commandButton value="Log Out" styleClass="stdButton" action="#{loginController.logout}" /></p>
    </h:body>      
</html>

DetentionTrackerAIP/web/WEB-INF/templates/header.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    
    <!-- This is the header template for the website. It displays the options of the website to the user throughout their navigation -->
    
    <h:head>
        <h:outputStylesheet  name="style.css" library="css" />
        <title><ui:insert name="title">Default Title</ui:insert></title>
    </h:head>
    <h:body>
    <table border="3" bordercolor="000000" style="width:100%;" cellpadding="0" cellspacing="0">
        <thead class="templatePageTableHeader">
            <tr>
                <th class="templatePageTableHeaderText" colspan="3">
                    <h1 class="h1"> Detention Tracker 1.0</h1>
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="templatePageTableRow">
                    <a href="create.xhtml"> <h2 class="h2">Create Detention</h2></a>
                </td>
                <td class="templatePageTableRow">
                    <a href="view.xhtml"> <h2 class="h2">View Detentions</h2></a>
                </td>
            </tr>            
        </tbody>
    </table>       
        <ui:insert name="content"> Default Content </ui:insert>
    </h:body>      
</html>

DetentionTrackerAIP/web/create.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
template="/WEB-INF/templates/header.xhtml"
xmlns:h="http://xmlns.jcp.org/jsf/html"
xmlns:f="http://java.sun.com/jsf/core">

    <!-- This allows a user to create a detention in the website. Fields are not able to use accent characters. First and Last name 
    input fields, in particular, can only use letters, apostrophes, dashes and single spaces. -->
    
    <ui:define name="title">
    Create a Detention
    </ui:define>
    <ui:define name="content">
        <h:head>
            <h:outputStylesheet  name="style.css" library="css" />
        </h:head>
        <h:body>
            <h1 class="h1">Create a Detention</h1>               
            <h:form>
                <div align="center">
                    <table>
                        <tr>
                            <td><h:outputText value="First Name: " styleClass="createHeader" /></td>
                            <td><h:inputText id="fname" value="#{detentionController.detention.FName}" styleClass="createInput" validatorMessage="You must enter a valid first name"/> </td>
                            <td><h:message for="fname" styleClass="createInputError"/></td>
                        </tr>
                        <tr>
                            <td><h:outputText value="Last Name: " styleClass="createHeader" /></td>
                            <td><h:inputText id="lname" value="#{detentionController.detention.LName}" styleClass="createInput" validatorMessage="You must enter a valid last name"/></td>
                            <td><h:message for="lname" styleClass="createInputError"/></td>
                        </tr>
                        <tr>
                            <td><h:outputText value="Year: " styleClass="createHeader"/></td>
                            <td><h:selectOneMenu  value="#{detentionController.detention.year}"  styleClass="createInput" >
                                    <f:selectItem itemValue="07" itemLabel="07"/>
                                    <f:selectItem itemValue="08" itemLabel="08"/>
                                    <f:selectItem itemValue="09" itemLabel="09"/>
                                    <f:selectItem itemValue="10" itemLabel="10"/>
                                    <f:selectItem itemValue="11" itemLabel="11"/>
                                    <f:selectItem itemValue="12" itemLabel="12"/>
                                </h:selectOneMenu></td>
                        </tr>
                        <tr>
                            <td><h:outputText value="Type of Detention: " styleClass="createHeader"/></td>
                            <td><h:selectOneMenu value="#{detentionController.detention.type}" styleClass="createInput">
                                    <f:selectItem itemValue="Afternoon" itemLabel="Afternoon"/>
                                    <f:selectItem itemValue="Morning" itemLabel="Morning"/>
                                    <f:selectItem itemValue="Saturday" itemLabel="Saturday"/>
                                    <f:selectItem itemValue="Lunchtime" itemLabel="Lunchtime"/>
                                </h:selectOneMenu></td>
                        </tr>
                        <tr>
                            <td><h:outputText value="Department: " styleClass="createHeader" /></td>
                            <td><h:selectOneMenu value="#{detentionController.detention.dept}" styleClass="createInput">
                                    <f:selectItem itemValue="Computing" itemLabel="Computing"/>
                                    <f:selectItem itemValue="Math" itemLabel="Math"/>
                                    <f:selectItem itemValue="English" itemLabel="English"/>
                                    <f:selectItem itemValue="Science" itemLabel="Science"/>
                                    <f:selectItem itemValue="HSIE" itemLabel="HSIE"/>
                                </h:selectOneMenu></td>
                        </tr>
                        <tr>
                            <td><h:outputText value="Reason: " styleClass="createHeader"/></td>
                            <td><h:inputText id="reason" styleClass="createInput" value="#{detentionController.detention.reason}" validatorMessage="You must enter a valid reason (check your input!)"/></td>
                            <td><h:message for="reason" styleClass="createInputError"/></td>
                        </tr>
                        <tr>
                            <td> </td>
                            <td>
                                <h:button value="Cancel"  styleClass="stdButton" outcome="cancel"/>
                                <h:commandButton value="Create" styleClass="stdButton" action="#{detentionController.createDetention()}"/>
                            </td>
                        </tr>
                    </table>
                </div>
            </h:form>
        </h:body>
    </ui:define>
</ui:composition>

DetentionTrackerAIP/web/edit.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
template="/WEB-INF/templates/header.xhtml"
xmlns:h="http://xmlns.jcp.org/jsf/html"
xmlns:f="http://java.sun.com/jsf/core">

    <!-- This allows a user to edit a detention. A detentions details are pre-loaded into the various fields on the page. 
    If a user tries to edit the fields with accent characters, an error will be displayed. In particular, the first and last
    name input fields can only use letters, apostrophes, dashes and single spaces-->
    
    <ui:define name="title">
    Edit a Detention
    </ui:define>
    <f:metadata>
        <f:viewAction action="#{detentionController.loadDetention(param.index)}"/>
    </f:metadata>    
    <ui:define name="content">     
        <h:head>
            <h:outputStylesheet  name="style.css" library="css" />
        </h:head>
        <h:body>
            <h1 class="h1">Edit a Detention</h1>        
            <h:form>
                <div align="center">
                    <table>
                        <tr>
                            <td><h:outputText value="First Name: " styleClass="createHeader" /></td>
                            <td><h:inputText id="fname" value="#{detentionController.detention.FName}" 
                                             validatorMessage="You must enter a valid first name!" styleClass="createInput"/> </td>
                            <td><h:message for="fname" styleClass="createInputError"/></td>
                        </tr>
                        <tr>
                            <td><h:outputText value="Last Name: " styleClass="createHeader" /></td>
                            <td><h:inputText id="lname" value="#{detentionController.detention.LName}" 
                                             validatorMessage="You must enter a valid last name" styleClass="createInput"/></td>
                            <td><h:message for="lname" styleClass="createInputError" /></td>
                        </tr>
                        <tr>
                            <td><h:outputText value="Year: " styleClass="createHeader" /></td>
                            <td><h:selectOneMenu value="#{detentionController.detention.year}" styleClass="createInput">
                                <f:selectItem itemValue="07" itemLabel="07"/>
                                <f:selectItem itemValue="08" itemLabel="08"/>
                                <f:selectItem itemValue="09" itemLabel="09"/>
                                <f:selectItem itemValue="10" itemLabel="10"/>
                                <f:selectItem itemValue="11" itemLabel="11"/>
                                <f:selectItem itemValue="12" itemLabel="12"/>
                            </h:selectOneMenu></td>
                        </tr>                              
                        <tr>
                            <td><h:outputText value="Type of Detention: " styleClass="createHeader" /></td>
                            <td><h:selectOneMenu value="#{detentionController.detention.type}" styleClass="createInput">
                                    <f:selectItem itemValue="Afternoon" itemLabel="Afternoon"/>
                                    <f:selectItem itemValue="Morning" itemLabel="Morning"/>
                                    <f:selectItem itemValue="Saturday" itemLabel="Saturday"/>
                                    <f:selectItem itemValue="Lunchtime" itemLabel="Lunchtime"/>
                                </h:selectOneMenu></td>
                        </tr>                              
                        <tr>
                            <td><h:outputText value="Department: " styleClass="createHeader" /></td>
                            <td><h:selectOneMenu value="#{detentionController.detention.dept}" styleClass="createInput">
                                    <f:selectItem itemValue="Computing" itemLabel="Computing"/>
                                    <f:selectItem itemValue="Math" itemLabel="Math"/>
                                    <f:selectItem itemValue="English" itemLabel="English"/>
                                    <f:selectItem itemValue="Science" itemLabel="Science"/>
                                    <f:selectItem itemValue="HSIE" itemLabel="HSIE"/>
                                </h:selectOneMenu></td>
                        </tr>                               
                        <tr>
                            <td><h:outputText value="Reason: " styleClass="createHeader" /></td>
                            <td><h:inputText id="reason" value="#{detentionController.detention.reason}" styleClass="createInput" validatorMessage="You must enter a valid reason (check your input!)"/></td>
                            <td><h:message for="reason" styleClass="createInputError" /></td>
                        </tr>
                        <tr>
                            <h:inputHidden value="#{detentionController.detention.id}"/>
                            <td>
                                <h:button value="Cancel"  styleClass="stdButton" outcome="cancel"/>
                                <h:commandButton value="Save" styleClass="stdButton" action="#{detentionController.editDetention()}"/>
                            </td>        
                        </tr>
                    </table>
                </div>         
            </h:form>
        </h:body>
    </ui:define>
</ui:composition>

DetentionTrackerAIP/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        Hello from Facelets
    </h:body>
</html>

DetentionTrackerAIP/web/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
template="/WEB-INF/templates/header.xhtml"
xmlns:h="http://xmlns.jcp.org/jsf/html"
xmlns:f="http://java.sun.com/jsf/core">

    <!-- This is the page that the user logs into. If the login process fails, the user is informed through an error -->
    
    <ui:define name="title">
    Login
    </ui:define>
    <ui:define name="content">
        <h:head>
            <h:outputStylesheet  name="style.css" library="css" />
        </h:head>
        <h:body>
            <h1 class="h1">Login</h1>               
            <h:form>
                <div align="center">
                    <h:messages errorClass="info"   styleClass="createInputError"/>
                    <table>        
                        <tr>
                            <td><h:outputText value="Username: " styleClass="createHeader"/></td>
                            <td><h:inputText id="username" value="#{loginController.username}" styleClass="createInput"/> </td>
                        </tr>
                        <tr>
                            <td><h:outputText value="Password: " styleClass="createHeader" /></td>
                            <td><h:inputSecret value="#{loginController.password}" styleClass="createInput"/></td>
                        </tr>
                            <td> </td>
                            <td><h:commandButton value="Login" action="#{loginController.login}" styleClass="stdButton"/>
                        </td>
                    </table>       
                    <hr></hr>
                    <h:commandLink value="Register" action="register" styleClass="stdLink"/>       
                </div>
            </h:form>
        </h:body>
    </ui:define>
</ui:composition>

DetentionTrackerAIP/web/register.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
template="/WEB-INF/templates/header.xhtml"
xmlns:h="http://xmlns.jcp.org/jsf/html"
xmlns:f="http://java.sun.com/jsf/core">

    <!-- This page allows a user to register with the website. Username and passwords must only have letters or numbers.
    An error is displayed if a username or password uses the wrong characters or if a username already exists.-->
    
    <ui:define name="title">
    Register
    </ui:define>
    <ui:define name="content">
        <h:head>
            <h:outputStylesheet  name="style.css" library="css" />
        </h:head>
        <h:body>
            <h1 class="h1">Create an Account</h1>               
            <h:form>
                <div align="center">
                    <h:messages errorClass="info" styleClass="createInputError"/>
                    <table>
                        <tr>
                            <td><h:outputText value="Username: " styleClass="createHeader" /></td>
                            <td><h:inputText id="username" styleClass="createInput" value="#{loginController.login.username}" validatorMessage="You must enter a valid username (letters and numbers only!)"/> </td>
                        </tr>
                        <tr>
                            <td><h:outputText value="Password: " styleClass="createHeader"/></td>
                            <td><h:inputSecret id="password" styleClass="createInput" value="#{loginController.login.password}" validatorMessage="You must enter a valid password (letters and numbers only!)"/></td>
                        </tr>
                            <td></td>
                            <td><h:commandButton value="Create Account" styleClass="stdButton" action="#{loginController.createUser}"/></td>
                    </table>
                </div>
            </h:form>
        </h:body>
    </ui:define>
</ui:composition>

DetentionTrackerAIP/web/view.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
template="/WEB-INF/templates/header.xhtml"
xmlns:h="http://xmlns.jcp.org/jsf/html"
xmlns:f="http://xmlns.jcp.org/jsf/core"
xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <!-- This page displays the current detentions to the user. If there are no detentions, then a message
    informing the user that there are none is displayed -->
    
    <ui:define name="title">
    View Detentions
    </ui:define>
        <ui:define name="content">
            <h:head>
                <h:outputStylesheet  name="style.css" library="css" />
            </h:head>
        <h:body>
            <h1 class="h1">Current Detentions</h1>        
            <div align="center">          
                <!-- Only displays the dataTable if the size of the detention list is greater than 0 -->
                <h:form rendered="#{detentionController.sizeOfDetentionList()!= 0}">
                    <h:dataTable styleClass="stdRowText" border="1" var="detention"  value="#{detentionController.allDetentions}">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="First Name" styleClass="stdRowHeader"/>
                            </f:facet>
                            <h:outputText value="#{detention.FName}"/>
                        </h:column>               
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Last Name" styleClass="stdRowHeader"/>
                            </f:facet>
                            <h:outputText value="#{detention.LName}"/>
                        </h:column>                
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Year" styleClass="stdRowHeader"/>
                            </f:facet>
                            <h:outputText value="#{detention.year}"/>
                        </h:column>                
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Type" styleClass="stdRowHeader"/>
                            </f:facet>
                            <h:outputText value="#{detention.type}"/>
                        </h:column>                
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Department" styleClass="stdRowHeader"/>
                            </f:facet>
                            <h:outputText value="#{detention.dept}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header" >
                                <h:outputText value="Reason" styleClass="stdRowHeader"/>
                            </f:facet>
                            <h:outputText value="#{detention.reason}"/>
                        </h:column>               
                        <h:column>
                            <h:button value="Edit" styleClass="stdButton" outcome="edit">
                                <f:param name="index" value="#{detention.id}"/>
                            </h:button>
                        </h:column>               
                        <h:column >
                            <h:commandButton value="Remove" styleClass="stdButton" action="#{detentionController.removeDetention(detention.id)}" />
                        </h:column>        
                    </h:dataTable>
                </h:form>
                <!-- Output text is rendered only if the size of the detention list is 0 -->
                <h:outputText rendered="#{detentionController.sizeOfDetentionList() == 0}" styleClass="stdRowHeader" value="No detentions to view!" />
            </div>
            <h:form>
                <ui:insert name="footer">
                    <ui:include src="/WEB-INF/templates/footer.xhtml" />
                </ui:insert>
            </h:form>
        </h:body>
    </ui:define>
</ui:composition>

DetentionTrackerAIP/web/welcome.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
template="/WEB-INF/templates/header.xhtml"
xmlns:h="http://xmlns.jcp.org/jsf/html">

    <!-- This page presents a welcome screen to the user when they log into the website -->
    
    <ui:define name="title">
    Welcome!
    </ui:define>
    <ui:define name="content">  
        <h:form>
            <h:head>
                <h:outputStylesheet  name="style.css" library="css" />
            </h:head>
            <h:body>
                <h1 class="h1">Welcome!</h1>
                <p class="stdRowHeader" >Please select what you would like to do from above.</p>
                <ui:insert name="footer">
                    <ui:include src="/WEB-INF/templates/footer.xhtml" />
                </ui:insert>
            </h:body>
        </h:form>
    </ui:define>
</ui:composition>